name: pencatat_keuangan
description: "Aplikasi Pencatat Keuangan Pribadi"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # HTTP & API
  dio: ^5.7.0

  # Local Storage
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.1

  # Charts
  fl_chart: ^0.70.2

  # Formatting & Fonts
  intl: ^0.19.0
  google_fonts: ^6.2.1

  # File & Export
  path_provider: ^2.1.5
  csv: ^6.0.0
  pdf: ^3.11.2
  printing: ^5.13.4

  # UI Enhancements
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
